#!/bin/bash

BOLD="\e[1m"
RESET="\e[0m"
RED="$BOLD\e[31m"
BLUE="$BOLD\e[34m"

input() {
  echo -ne "${BLUE}=>${RESET}${BOLD} $1${RESET}"
}

err() {
  echo -e "${RED}=>${RESET}${BOLD} $1${RESET}"
}

export USUM="$(echo $RANDOM$RANDOM$RANDOM | md5sum | awk '{print $1}')"
input "Connection IP [string]: "
read ip 
input "Connection Port [1-65535]: "
read port 
input "Debug mode [true/false]: "
read debug

if [ "$debug" != "true" ] && [ "$debug" != "false" ];
then
  err "Bad debug option"
  exit 1
fi

cat > inc/config.h << EOF
// config generated by conf.sh
#define USUM "$USUM"
#define IP "$ip"
#define PORT $port 
#define DEBUG $debug 
EOF
